### PR TITLE
Fix getrandom on Ubuntu 16.04 (GLIBC 2.23)

### LINKED ISSUE #13: getrandom not found on Ubuntu 16.04 (GLIBC 2.23)
I tried to compile `mirage-crypto` and on my distribution, `sys/random.h` does not exist - and appears only on >= GLIBC.2.25 (according to [changelog](https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html)).

I did this little patch to be able to compile `mirage-crypto` on my side:
```diff
diff --git a/rng/unix/mc_getrandom_stubs.c b/rng/unix/mc_getrandom_stubs.c
index fc8b741..9a4f849 100644
--- a/rng/unix/mc_getrandom_stubs.c
+++ b/rng/unix/mc_getrandom_stubs.c
@@ -6,9 +6,11 @@
 #include <caml/bigarray.h>
 
 #if defined(__linux)
+# include <errno.h>
 // on Linux, we use getrandom and loop
-#include <sys/random.h>
-#include <errno.h>
+
+# if __GLIBC__ > 2 || __GLIBC_MINOR__ > 24
+# include <sys/random.h>
 
 void raw_getrandom (uint8_t *data, uint32_t len) {
   int r, off = 0;
@@ -19,6 +21,19 @@ void raw_getrandom (uint8_t *data, uint32_t len) {
     off += r;
   }
 }
+#else
+# include <sys/syscall.h>
+
+void raw_getrandom (uint8_t *data, uint32_t len) {
+  int r, off = 0;
+  while (off < len) {
+    r = syscall(SYS_getrandom, data + off, len - off, 0);
+    if (r < 0 && errno == EINTR) continue;
+    else if (r < 0) uerror("getrandom", Nothing);
+    off += r;
+  }
+}
+#endif
 
 #elif (defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__APPLE__))
 // on BSD and macOS, loop (in pieces of 256) getentropy
```

### PR DESCRIPTION
**Pull request by dinosaure**
Fix #13

### CODE REVIEW

File: rng/unix/mc_getrandom_stubs.c [hunk 1]
```diff
@@ -6,9 +6,11 @@
 #include <caml/bigarray.h>
 
 #if defined(__linux)
+# include <errno.h>
 // on Linux, we use getrandom and loop
-#include <sys/random.h>
-#include <errno.h>
+
+# if __GLIBC__ > 2 || __GLIBC_MINOR__ > 24
```
Comment (hannesm) [inline rng/unix/mc_getrandom_stubs.c]: for musl/uclibc this `if` is wrong
```
#if __GLIBC__ && (__GLIBC__ > 2 || __GLIBC_MINOR__ > 24)
```

should do the trick :)

Comment (hannesm) [reply rng/unix/mc_getrandom_stubs.c]: hmm no, likely easiest to invert the cases ;)

```
#if __GLIBC__ && __GLIBC__ <= 2 && __GLIBC_MINOR__ < 25
..do the syscall manually..
#else
..call getrandom(`..
```

**Comment by hannesm** [comment]
since the C code is mostly identical, why not use
```
#include <sys/random.h>
#define getrandom_call getrandom
```
in the default, and for glibs < 2.25 
```
#include <sys/syscall.h>
#define getrandom_call SYS_getrandom
```
?
